name: Update NFL Data

on:
  schedule:
    - cron: '0 6 * * *'
  #  - cron: '0 8 * * *'    
  #  - cron: '0 4 * * 1'
  #  - cron: '0 12 * * 0'
  #  - cron: '0 12 * * 6' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: puntersloveit
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: update nfl data
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python scripts/update_nfl_data.py
        
      - name: Commit to the repo
        run: |
          git config --global user.name 'superserejka'
          git config --global user.email 'superserejka@users.noreply.github.com'
          git add .
          git commit -am "updated files"
          git push
